on: workflow_dispatch
name: binary
jobs:
  get-build-artifact:
    name: Get Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1.0"

      - name: Install Dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build --profile=release @install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: towerfmt-server_x86-64
          path: _build/install/default/bin/towerfmt-server

